apiVersion: v1
kind: Pod
metadata:
  name: nginx-date-pod
spec:
  containers:
  - name: nginx
    image: nginx
  - name: date
    image: busybox
    command: ["sh", "-c", "while true; do date >> /html/index.html; sleep 1; done"]
  volumeMounts:
  - name: html
    mountPath: /html
  volumes:
  - name: html
    emptyDir: {}
