apiVersion: batch/v1
kind: Job
metadata:
  name: gsutil-sync-job
spec:
  template:
    spec:
      containers:
      - name: gsutil-sync
        image: google/cloud-sdk:275.0.0-alpine
        command: ["gsutil", "-m", "rsync", "-dr", "gs://glow-sportradar/", "/data/input"]
        volumeMounts:
        - name: glow-data-disk
          mountPath: /data
      restartPolicy: Never
      volumes:
      - name: glow-data-disk
        gcePersistentDisk:
          pdName: glow-data-disk-200
  backoffLimit: 0
