apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
spec:
  containers:
  - name: redis
    image: redis
    env:
    - name: REDIS_USER
      valueFrom:
        secretKeyRef:
          name: mysecret1
          key: username
    - name: REDIS_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysecret1
          key: password
